Remove time zone information from dividends
The master DF doesn't contain TZ information either but its presence in
dividends DF prevents the two being merged together.

Error:
ValueError: You are trying to merge on datetime64[ns] and datetime64[ns,
America/New_York] columns for key 'Date'. If you wish to proceed you
should use pd.concat