Drop "Ticker" level from now-MultiIndex Yahoo Finance DataFrame
It's not supported and causes various issues like:

pandas.errors.MergeError: Not allowed to merge between different levels.
(2 levels on the left, 1 on the right)